baseURL = "https://2ec91f745954.restoration-lab.net/"
title = "Restoration Lab"
author = "Restoration Lab Web Admin"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# disable taxonomy and categories
disableKinds = ["taxonomy", "term"]

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Restoration Lab Logo - Letters R and L around a graphic depiction of a human spine"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Restoration Lab"
    header = "Welcome to the Restoration Lab"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Restoration Lab - An Albuquerque clinic of Naprapathic Medicine"
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "https://restoration-lab.net"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2

  [[menu.main]]
    identifier = "team"
    name = "Our Team"
    url = "/team/"
    weight = 3

  [[menu.main]]
    identifier = "booknow"
    name = "Online Booking"
    url = "/booknow/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Contact Us"
    url = "/contact/"
    weight = 2
