name: test hugo build

on:
  pull_request:
    branches:
      - master # PRs to master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup build dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Test build
        run: hugo --minify
